package services;

import musicBot.AudioEventHandler;
import start.RuntimeVariables;

public class Help {

	public final static String HELPTEXT = ">>> Ich verstehe folgende Befehle:\n"
			+ "`Hey Megumin`: Lass dich von mir begrüßen! :smile:\n"
			+ "`MegHelpMusik`: Alles zu Musik! :musical_note:\n"
			+ "`MegHelpUmfrage`: Alles zu Umfragen! :bar_chart:\n"
			+ "`MegJisho WORT`: Englisch <--> Japanisch Wörterbuch (Quelle: jisho.org) :flag_jp: <--> :flag_gb:\n"
			+ "`MegRomaji TEXT`: Hiragana/Katakana -> Lateinisches Alphabet :sa: --> :abc:\n"
			+ "`MegKatakana TEXT`: Lateinisches Alphabet -> Katakana :flag_jp:\n"
			+ "`MegZeit`: Aktuelle Uhrzeit und aktuelles Datum (deutsche Zeit)! :clock1:\n"
			+ "`MegStatus`: Aktuelle Statusinformationen zu meiner Existenz :signal_strength:\n"
			+ "`MegSchreiben/Sprechen TEXT`: Ich plappere dir nach, denn deine Worte sind weise! :blush:\n"
			+ "`MegHelp`: Siehst du gerade vor dir, baka!\n"
			+ "\n"
			+ "**VERSION "+RuntimeVariables.VERSION+" "+(RuntimeVariables.IS_DEBUG ? "(EXPERIMENTELL)":"")+"**"
			+ "\n"
			+ "Fragen, Anregungen und Vorschläge können gerne Maxim oder auf GitHub gestellt werden:\n"
			+ RuntimeVariables.GIT_URL;
	
	public final static String MUSICHELPTEXT = ">>> Du möchtest deine Freunde mit deiner furchtbaren Musik nerven? Ich helfe dir dabei! :musical_note:\n\n"
			+ "*Du musst für die meisten Befehle selber im VoiceChannel sein!*\n"
			+ "`MegMusik YTSUCHE/URL`: Ich spiele Musik anhand eines Youtube- SoundCloud- oder Bandcamp-Links ab! Alternativ kannst du auch einfach ein Wort eingeben "
			+ "und ich werde danach auf YouTube suchen!"
			+ (AudioEventHandler.MUSIC_WARN.length() > 0 ? "\n"+AudioEventHandler.MUSIC_WARN+"\n" : "")
			+ "\n"
			+ "`MegMusikNext OPT.ANZAHL`: Ich spiele den nächsten Track aus der Warteschlange ab! Du kannst nach einem Leerzeichen auch eine Zahl mitgeben, ich überspringe dann "
			+ "entsprechend viele Tracks!"
			+ "\n"
			+ "`MegMusikPause`: Pausiere die Musik! :pause_button:"
			+ "\n"
			+ "`MegMusikPlay`: Antipausiere die Musik! :arrow_forward:"
			+ "\n"
			+ "`MegMusikStop`: Beende die Musikwiedergabe und lösche die Warteschlange :stop_button:"
			+ "\n"
			+ "`MegMusikQueue`: Aktuelle Wiedergabe und Warteschlange"
			+ "\n"
			+ "`MegMusikVol`: Ich nenne dir meine aktuelle Lautstärke! (Das Ändern der Lautstärke ist Admins vorbehalten)";
	
	public final static String ADMHELP = ">>> Du hast Zugriffsrechte auf Admin Befehle! :man_office_worker:\n"
			+ "`MegLogout`: Ich melde mich ab und terminiere (bitte nur im Notfall verwenden) :skull_crossbones:"
			+ "\n"
			+"`MegKill`: Terminiert im Gegensatz zu 'MegLogout' unverzüglich und ohne Nachrichten CleanUp (für den Fall, dass 'MegLogout' nicht funktioniert)."
			+ "\n"
			+ "`MegMusikVol ZAHL`: Ich ändere meine Lautstärke!";
	
	public final static String SURVEYHELPTEXT = ">>> So nutzt du die Macht der Umfragen!"
			+ "\n"
			+ "Tipp: Copy & paste **fettgedruckte Befehle**, dies reduziert Syntaxfehler!"
			+ "\n"
			+ "\n"
			+ "__Neue Umfrage starten__\n**MegUmfrage BESCHREIBUNG-OPTION A;OPTION B-ZEIT IN MINUTEN**"
			+ "\n"
			+ "Erzeugt eine Umfrage mit einer erlaubten Antwort pro User. Die Beschreibung darf Leerzeichen enthalten! Darauffolgende Argumente fangen mit"
			+ "\n"
			+ "einem Bindestrich an (und dürfen auch Leerzeichen enthalten!). Antwortmöglichkeiten werden mit Semikolon getrennt. "
			+ "Zum Schluss gibst du am Ende an, wie lange"
			+ "\n"
			+ "(in Minuten und als ganze Zahl) die Umfrage dauern soll. Für deine Umfrage wird automtisch eine freie ID ermittelt, sie wird für andere Befehle benötigt."
			+ "\n"
			+ "*Beispiel für eine 30-minütige Umfrage: MegUmfrage Welche Farbe bevorzugst du?-Rot;Grün;Blau-30*"
			+ "\n"
			+ "\n"
			+ "__Mehrfache Antwortmöglichkeiten__\n**MegMultiUmfrage BESCHREIBUNG-OPTION A;OPTION B-ZEIT IN MINUTEN**"
			+ "\n"
			+ "Erzeugt eine Umfrage, in der jeder User für mehrere Antworten gleichzeitig abstimmen kann."
			+ "\n"
			+ "Ansonsten ist alles so, wie in 'MegUmfrage' auch."
			+ "\n"
			+ "\n"
			+ "*Tipp für Zeitangaben:*"
			+ "\n"
			+ "60 = 1 Stunde, 720 = 12h, 1440 = 24h, 10080 = 1 Woche, 43200 = 1 Monat (30 Tage), 525600 = 1 Jahr, "+Integer.MAX_VALUE+" (maximum) = 4000+ Jahre"
			+ "\n"
			+ "\n"
			+ "__Antwort senden, löschen und überschreiben__"
			+ "\n"
			+ "**MegUmfrage ID-NUMMER DEINER ANTWORT**"
			+ "\n"
			+ "Gib als erstes Argument die zugehörige Umfrage-ID (also z.B. 1) an. Die ID steht weiter unten in der Umfrage.\nHinter einem Bindestrich schreibst du dann "
			+ "die Nummer deiner Antwort."
			+ "\n"
			+ "Schreib den selben Befehl nochmal, um die Antwort wieder zu löschen. Wenn du bereits für etwas anderes abgestimmt hast und mehrfache Antworten aus sind,"
			+ "\n"
			+ "wird deine alte Stimme überschrieben!"
			+ "\n"
			+ "*Beispiel Vote für 2.Option in Umfrage Nr.1: MegUmfrage 1-2*"
			+ "\n"
			+ "\n"
			+ "__Alle Antworten löschen__\n**MegLeaveUmfrage ID**"
			+ "\n"
			+ "Ich lösche alle deine Stimmen aus einer Umfrage."
			+ "\n"
			+ "*Beispiel: MegLeaveUmfrage 1*";
}
